### ISSUE TITLE
orderbook optional parameters limit_bids and limit_asks are set to 50

### ISSUE THREAD

**Issue by dutu** [lookfirst/bitfinex-promise#1]
limit_bids and limit_asks are optional for orderbook method.
When these parameter are not specified, the orderbook method should call the native API without the parameters.

Currently this is set to value 50.
https://github.com/lookfirst/bitfinex-promise/blob/master/lib/Bitfinex.js#L58

**Comment by lookfirst** [comment]
Sorry for the very late reply. I just noticed this issue and have no subscribed to future issue notifications. Thanks for reporting it. [According to the documentation](https://www.bitfinex.com/pages/api), the default is 50 when unspecified. If you need more or less than that, you should specify a number. :smile:

**Comment by dutu** [comment]
Wrapper module should pass the parameters as received and should not set any unspecified parameters to a hard-coded value

----- Reply message -----

**Comment by lookfirst** [comment]
I'll accept a pr.
