### ISSUE TITLE
In POST, the path in the request should include /v1/

### ISSUE THREAD

**Issue by jsgoyette** [lookfirst/bitfinex-promise#2]
In the POST request (used for private endpoints) the path should also include "/v1/". For example, now for the pastTrades the path in the request is "mytrades", but instead it should be "/v1/mytrades". 

I was not able to get calls to private endpoints to work without this change.

**Comment by lookfirst** [comment]
Fixed in https://github.com/lookfirst/bitfinex-promise/pull/5
