### ISSUE TITLE
Certain private endpoint methods failing due to no params

### ISSUE THREAD

**Issue by jsgoyette** [lookfirst/bitfinex-promise#4]
Some of the methods to call private endpoints are not passing a params object to the _makePrivateRequest method, and thus the payload fails to build in the _makeRequestObject method. I'd suggest the following (line 139 in the coffee source): 

payload = params || {}

**Comment by lookfirst** [comment]
Fixed in https://github.com/lookfirst/bitfinex-promise/pull/5
